### ISSUE TITLE
Support higher versions of i18n

### ISSUE THREAD

**Issue by oleksandra-k** [kyledecot/vindetta#10]
Hi, @kyledecot!
Thank you for your lib. We are using it, but recently we have had an issue with an outdated version of i18n 

Fix is very simple:

```
spec.add_dependency "i18n", "> 0.8", "<2"
```
Could it be implemented ASAP?

Thank you in advance

**Comment by kyledecot** [comment]
Hi @oleksandra-k if you submit a pull request I can merge this in for you.

**Comment by oleksandra-k** [comment]
I was trying, but for some reason - I can't

**Comment by oleksandra-k** [comment]
I solved the problem and created PR https://github.com/kyledecot/vindetta/pull/11

**Comment by oleksandra-k** [comment]
hi, @kyledecot ! thanks for merging! Can I ask you to release it as new version, also?

**Comment by oleksandra-k** [comment]
@kyledecot kind reminder

**Comment by kyledecot** [comment]
This has been released to rubygems 🎉 Thanks again for the contribution.

**Comment by oleksandra-k** [comment]
but I don't see new version
<img width="803" alt="image" src="https://user-images.githubusercontent.com/56920003/175896612-139419dd-a377-4364-9f01-90c5b7854090.png">
