### ISSUE TITLE
Please release new version of gem

### ISSUE THREAD

**Issue by oleksandra-k** [kyledecot/vindetta#12]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/56920003/175922035-43498a6f-76a4-48c6-9d14-790153c8d4fb.png">
I've tried - support of i18n with higher versions did not apply

**Comment by kyledecot** [comment]
Not sure what happened but I ran my release script again and it works this time 🎉 

<img width="1011" alt="Screen Shot 2022-06-28 at 8 26 23 AM" src="https://user-images.githubusercontent.com/192464/176178200-c17b3cef-cfe6-4a3c-bcf9-15966aa865f8.png">
