### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by jeremylynch** [kyledecot/vindetta#2]
The following doesn't seem to work: 
```
vindetta command
```

**Comment by kyledecot** [comment]
Hi @jeremylynch "command" here is just a placeholder for the actual command that you're attempting to run. For example if you want to generate a VIN you can use:

```ruby
vindetta generate
```

If you want to decode a VIN you can use:

```ruby
vindetta decode SOME_VIN_HERE
```

You can get a full list of commands by typing:

```
vindetta --help
```
